[tool.poetry]
name = "dremio-demo"
version = "0.1.0"
description = ""
authors = ["Adi Wabisabi <technobabelfish@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
