resources:
  - name: dremio-demo
    type: git
    icon: github
    source:
      uri: https://github.com/timeartist/dremio-demo
      branch: main
  - name: dremio-demo-container
    type: registry-image
    icon: docker
    source:
      repository: ((docker-user))/dremio-concourse-demo
      username: ((docker-user))
      password: ((docker-access-token))

jobs: 
  - name: ls
    plan:
      - get: dremio-demo
        trigger: true
      - task: show-contents
        privileged: true
        file: dremio-demo/ci/show-contents.yml
  - name: build-dremio-demo-container
    plan:
      - get: dremio-demo
        trigger: true
        passed: [ls]
      - task: build
        privileged: true
        file: dremio-demo/ci/build.yml
      - put: dremio-demo-container
        params:
          image: image/image.tar
          version: 99.99.99
          bump_aliases: true
  - name: test
    plan:
      - get: dremio-demo-container
        trigger: true
        passed: [build-dremio-demo-container]
      - task: test
        privileged: true
        file: dremio-demo/ci/test.yml