resources:
  - name: dremio-demo
    type: git
    icon: github
    source:
      uri: https://github.com/timeartist/dremio-demo
      branch: main
  - name: dremio-demo-container
    type: registry-image
    icon: docker
    source:
      repository: ((docker-user))/dremio-concourse-demo
      username: ((docker-user))
      password: ((docker-access-token))
  - name: dremio-demo-container-stage
    type: registry-image
    icon: docker
    source:
      repository: ((docker-user))/dremio-concourse-demo-stage
      username: ((docker-user))
      password: ((docker-access-token))
jobs: 
  - name: show-contents
    plan:
      - get: dremio-demo
        trigger: true
      - task: show-contents
        privileged: true
        file: dremio-demo/ci/show-contents.yml
  - name: build-dremio-demo-container
    plan:
      - get: dremio-demo
        trigger: true
        passed: [show-contents]
      - task: build
        privileged: true
        file: dremio-demo/ci/build.yml
      - put: dremio-demo-container-stage
        params:
          image: image/image.tar
          version: 99.99.99
          bump_aliases: true
  - name: test
    plan:
      - get: dremio-demo
        trigger: true
        passed: [build-dremio-demo-container]
      - get: dremio-demo-container-stage
        trigger: true
        passed: [build-dremio-demo-container]
        params: 
          format: oci
      - task: test
        privileged: true
        file: dremio-demo/ci/test-v2.yml
      - put: dremio-demo-container
        params:
          image: dremio-demo-container-stage/image.tar
          version: 99.99.99
          bump_aliases: true
